local function printHelp()
    print("Usage: trx.[command]")
    print("")
    print("Commands:")
    print("  transmit    tx rx message")
    print("  |           tx Channel to send message on")
    print("  |           rx Channel for replies")
    print("  |           message Message to send")
    print("")
    print("  receiver    rx")
    print("  |           Prints messages recieved on rx")
    print("")
    print("  close       channel")
    print("  |           channel Closes given channel")
    print("")
    print("  closeAll    Closes all open channels")
end

printHelp()